services:
  olist-postgres:
    image: postgres:bullseye
    container_name: olist-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gabfxv
      POSTGRES_PASSWORD: password
      POSTGRES_DB: olist
    ports:
      - "5543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - olist-shared-network

  olist-minio:
    image: minio/minio:latest
    container_name: olist-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: gabfxv
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # Console Web
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - olist-shared-network

  dbt-docs:
    build:
      context: ./olist_elt
    container_name: dbt-docs
    ports:
      - "8081:8081"
    volumes:
      - ./olist_elt:/usr/app
      - dbt-exec:/root/.dbt
    restart: unless-stopped
    depends_on:
      - olist-postgres

volumes:
  postgres-data:
  minio-data:
  dbt-exec:
    external: true
  dbt-project:
    external: true

networks:
  olist-shared-network:
    external: true