services:
  olist-postgres:
    image: postgres:bullseye
    container_name: olist-postgres
    environment:
      POSTGRES_USER: gabfxv
      POSTGRES_PASSWORD: password
      POSTGRES_DB: olist
    ports:
      - "5543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - olist-shared-network

  olist-minio:
    image: minio/minio:latest
    container_name: olist-minio
    environment:
      MINIO_ROOT_USER: gabfxv
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # Console Web
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - olist-shared-network

volumes:
  postgres-data:
  minio-data:

networks:
  olist-shared-network:
    external: true