sources:
  - name: bronze
    database: olist
    schema: bronze
    description: Raw tables from Kaggle with no transformations applied; only redundancy added via PySpark.
    tables:
      - name: geolocation
        identifier: olist_geolocation_dataset
        description: Contains the locations of sellers and customers
        columns:
          - name: geolocation_zip_code_prefix
            description: "Zip code prefix for the geographical location."
            tests:
              - not_null
          - name: geolocation_lat
            description: "Latitude coordinate of the location."
            tests:
              - not_null
          - name: geolocation_lng
            description: "Longitude coordinate of the location."
            tests:
              - not_null
          - name: geolocation_city
            description: "City name of the geographical location."
            tests:
              - not_null
          - name: geolocation_state
            description: "State abbreviation of the geographical location."
            tests:
              - not_null

      - name: orders
        identifier: olist_orders_dataset
        description: Contains the details on orders performed on Olist, such as their customers, status and key dates.
        columns:
          - name: order_id
            description: "Unique identifier for each order."
            tests:
              - unique
              - not_null
          - name: customer_id
            description: "Identifier for the customer who placed the order."
            tests:
              - not_null
              - relationships:
                  to: source('bronze', 'customers')
                  field: customer_id
          - name: order_status
            description: "Current status of the order (e.g., shipped, delivered, canceled)."
            tests:
              - not_null
              - accepted_values:
                  values: ['shipped','unavailable','invoiced','created','approved','processing','delivered','canceled']
          - name: order_purchase_timestamp
            description: "Timestamp when the order was placed."
            tests:
              - not_null
          - name: order_approved_at
            description: "Timestamp when the order was approved."
          - name: order_delivered_carrier_date
            description: "Timestamp when the order was delivered to the carrier."
          - name: order_delivered_customer_date
            description: "Timestamp when the order was delivered to the customer."
          - name: order_estimated_delivery_date
            description: "Estimated date for the order delivery."
            tests:
              - not_null

      - name: payments
        identifier: olist_order_payments_dataset
        description: Contains the details of installments payments for an order, such as the specific installment, value and payment method.
        columns:
          - name: order_id
            description: "Identifier for the related order."
            tests:
              - not_null
              - relationships:
                  to: source('bronze', 'orders')
                  field: order_id
          - name: payment_sequential
            description: "Sequential number for the payment installment."
            tests:
              - not_null
          - name: payment_type
            description: "Method of payment used (credit card, boleto, voucher, etc.)."
            tests:
              - not_null
              - accepted_values:
                  values: ['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']
          - name: payment_installments
            description: "Number of installments for the payment."
            tests:
              - not_null
          - name: payment_value
            description: "Amount paid in this payment."
            tests:
              - not_null


      - name: products
        identifier: olist_products_dataset
        description: Contains details about the products available on Olist.
        columns:
          - name: product_id
            description: "Unique identifier for the product."
            tests:
              - not_null
              - unique
          - name: product_category_name
            description: "Category name of the product."
          - name: product_name_lenght
            description: "Length of the product's name."
          - name: product_description_lenght
            description: "Length of the product's description."
          - name: product_photos_qty
            description: "Number of photos available for the product."
          - name: product_weight_g
            description: "Weight of the product in grams."
          - name: product_length_cm
            description: "Length of the product in centimeters."
          - name: product_height_cm
            description: "Height of the product in centimeters."
          - name: product_width_cm
            description: "Width of the product in centimeters."


      - name: reviews
        identifier: olist_order_reviews_dataset
        description: Contains reviews on orders of Olist and associated metadata, such as timestamps.
        columns:
          - name: review_id
            description: "IMPORTANTE: há duplicação de reviews com mesmo review_id. Deveria ser unique sim!"
            tests:
              - not_null

          - name: order_id
            description: "Resolvido o problema do review_id de duplicação, provavelmente order_id se tornaria única"
            tests:
              - not_null
              - relationships:
                  to: source('bronze', 'orders')
                  field: order_id

          - name: review_score
            description: "Score given by the customer to the order (1 to 5)."
            tests:
              - not_null
              - accepted_values:
                  values: [1, 2, 3, 4, 5]

          - name: review_comment_title
            description: "Title of the customer's review comment."
          - name: review_comment_message
            description: "Detailed message of the customer's review comment."
          - name: review_creation_date
            description: "Date when the review was created."
            tests:
              - not_null

          - name: review_answer_timestamp
            description: "Timestamp when the review was answered by the seller."
            tests:
              - not_null


      - name: sellers
        identifier: olist_sellers_dataset
        description: Contains details about the sellers of Olist.
        columns:
          - name: seller_id
            description: "Unique identifier for each seller."
            tests:
              - unique
              - not_null
          - name: seller_zip_code_prefix
            description: "Zip code prefix of the seller's location."
            tests:
              - not_null
          - name: seller_city
            description: "City where the seller is located."
            tests:
              - not_null
          - name: seller_state
            description: "State abbreviation where the seller is located."
            tests:
              - not_null
              - relationships:
                  to: source('bronze', 'geolocation')
                  field: geolocation_state

      - name: order_items
        identifier: olist_order_items_dataset
        description: Contains details on the items that makes an order.
        columns:
          - name: order_id
            description: "Identifier of the order containing this item."
            tests:
              - not_null
              - relationships:
                  to: source('bronze', 'orders')
                  field: order_id
          - name: order_item_id
            description: "Sequential identifier of the item within the order."
            tests:
              - not_null
          - name: product_id
            description: "Identifier of the product in the order item."
            tests:
              - not_null
              - relationships:
                  to: source('bronze', 'products')
                  field: product_id
          - name: seller_id
            description: "Identifier of the seller for this order item."
            tests:
              - not_null
              - relationships:
                  to: source('bronze', 'sellers')
                  field: seller_id
          - name: shipping_limit_date
            description: "Deadline date to ship the order item."
            tests:
              - not_null
          - name: price
            description: "Price of the product in the order item."
            tests:
              - not_null
          - name: freight_value
            description: "Freight cost for shipping the order item."
            tests:
              - not_null

      - name: customers
        identifier: olist_customers_dataset
        description: Contains details about the customers of Olist.
        columns:
          - name: customer_id
            description: "Unique identifier for a customer for a specific order."
            tests:
              - not_null
              - unique
          - name: customer_unique_id
            description: "Unique identifier for the customer."
            tests:
              - not_null
          - name: customer_zip_code_prefix
            description: "Zip code prefix of the customer's address."
            tests:
              - not_null
          - name: customer_city
            description: "City where the customer resides."
            tests:
              - not_null
          - name: customer_state
            description: "State abbreviation where the customer resides."
            tests:
              - not_null
              - relationships:
                  to: source('bronze', 'geolocation')
                  field: geolocation_state

      - name: category_translation
        identifier: product_category_name_translation
        description: Contains the english translation of the product categories available on Olist.
        columns:
          - name: product_category_name
            description: "Product category name in the original language (Portuguese)."
            tests:
              - not_null
              - unique
              - relationships:
                  to: source('bronze', 'products')
                  field: product_category_name
          - name: product_category_name_english
            description: "Product category name translated to English."
            tests:
              - not_null
              - unique